[mongodb]
mongodb-dev.88sdaws.fun

[catalogue]
catalogue-dev.88sdaws.fun

[redis]
redis-dev.88sdaws.fun

[user]
user-dev.88sdaws.fun

[cart]
cart-dev.88sdaws.fun

[mysql]
mysql-dev.88sdaws.fun

[shipping]
shipping-dev.88sdaws.fun

[rabbitmq]
rabbitmq-dev.88sdaws.fun

[payment]
payment-dev.88sdaws.fun

[frontend]
frontend-dev.88sdaws.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.88sdaws.fun
CATALOGUE_HOST=catalogue-dev.88sdaws.fun
REDIS_HOST=redis-dev.88sdaws.fun
USER_HOST=user-dev.88sdaws.fun
CART_HOST=cart-dev.88sdaws.fun
MYQL_HOST=mysql-dev.88sdaws.fun
SHIPPING_HOST=shipping-dev.88sdaws.fun
RABBITMQ_HOST=rabbitmq-dev.88sdaws.fun
PAYMENT_HOST=payment-dev.88sdaws.fun





